const PRODUCTS=[["Wired Earphone","E20S"],["Wired Earphone","E300C"],["Wired Earphone","E100C"],["TWS","T100S"],["TWS","T206"],["TWS","T405"],["TWS","OPENFIT R1"],["TWS","EBC-01"],["TWS","OW7"],["TWS","OPEN EAR A1"],["Speaker","SF21 (15W)"],["Speaker","S7H"],["Speaker","SF7"],["Speaker","SV6"],["Speaker","SV16"],["Powerbank","P102S"],["Powerbank","P13"],["Smartwatch","META S1 LITE"],["Smartwatch","META S2 ULTRA"],["Smartwatch","FW6"],["Smartwatch","W16"],["Cable Data","D309BC"],["Cable Data","D306M"],["Cable Data","D306M REFILL"],["Cable Data","D306C"],["Charger","C308CC 20W"],["Charger","C113M"],["Charger","C113C"],["Cooler","CF3"],["Fan","PF9"],["Fan","PF11"]];
const COLORS=["PUTIH","HITAM","PINK","BEIGE","BIRU","MIX","Grey"],KEY_USER="Digifine",KEY_PASS="Gasspoll";
const sb=supabase.createClient("https://sqmctsakwkmizhfvzpih.supabase.co","sb_publishable_KpZj7PCKI4-9h38Bl3AydA_6uRyahvb");let stockIn=[],stockOut=[],channel;
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),money=n=>"Rp "+Number(n||0).toLocaleString("id-ID"),sku=(p,c)=>`${p}-${c}`.replaceAll(" ","-").replace(/[()]/g,"");
const pmap=()=>Object.fromEntries(PRODUCTS.map(p=>[p[1],{category:p[0]}]));
function opts(id,arr,all=false){$(id).innerHTML=(all?'<option value="">Semua</option>':"")+arr.map(x=>`<option value="${typeof x==="string"?x:x[1]}">${typeof x==="string"?x:x[1]}</option>`).join("")}
function empty(n){return `<tr><td colspan="${n}" class="muted">Belum ada data.</td></tr>`}
function getStock(p,c,d,excludeId=null){let a=stockIn.filter(x=>x.product===p&&x.color===c&&x.date<=d).reduce((s,x)=>s+x.qty,0),b=stockOut.filter(x=>x.id!==excludeId&&x.product===p&&x.color===c&&x.date<=d).reduce((s,x)=>s+x.qty,0);return a-b}
async function load(){const[a,b]=await Promise.all([sb.from("stock_in").select("*").order("date",{ascending:false}).order("id",{ascending:false}),sb.from("stock_out").select("*").order("date",{ascending:false}).order("id",{ascending:false})]);if(a.error||b.error){console.error(a.error||b.error);return alert("Gagal mengambil data online.");}stockIn=(a.data||[]).map(x=>({...x,id:+x.id,qty:+x.qty}));stockOut=(b.data||[]).map(x=>({...x,id:+x.id,qty:+x.qty,price:+x.price,total:+x.total}));render()}
function realtime(){channel=sb.channel("digifine-realtime").on("postgres_changes",{event:"*",schema:"public",table:"stock_in"},load).on("postgres_changes",{event:"*",schema:"public",table:"stock_out"},load).subscribe(s=>{const e=$("syncStatus");e.textContent=s==="SUBSCRIBED"?"● Realtime Aktif":"● "+s;e.classList.toggle("offline",s!=="SUBSCRIBED")})}
function showPage(p){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active-page"));$(p).classList.add("active-page");document.querySelectorAll(".nav-item[data-page]").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$("pageTitle").textContent={dashboard:"Dashboard",stockIn:"Stock In",stockOut:"Stock Out / Penjualan",liveStock:"Live Stock",reports:"Laporan",products:"Master Produk"}[p];render()}
function render(){dash();rin();rout();rlive();rreport();rprod();updateTotal()}
function dash(){let s=PRODUCTS.reduce((a,p)=>a+COLORS.reduce((b,c)=>b+Math.max(0,getStock(p[1],c,today())),0),0),o=stockOut.filter(x=>x.date===today());$("statSku").textContent=PRODUCTS.length*COLORS.length;$("statStock").textContent=s;$("statSales").textContent=o.reduce((a,x)=>a+x.qty,0);$("statRevenue").textContent=money(o.reduce((a,x)=>a+x.total,0));let ds=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let z=d.toISOString().slice(0,10);ds.push([z,stockOut.filter(x=>x.date===z).reduce((a,x)=>a+x.qty,0)])}let mx=Math.max(1,...ds.map(x=>x[1]));$("salesChart").innerHTML=ds.map(x=>`<div class="bar-wrap"><b>${x[1]}</b><div class="bar" style="height:${Math.max(3,x[1]/mx*145)}px"></div><small>${x[0].slice(5)}</small></div>`).join("");let c={};o.forEach(x=>{let m=pmap()[x.product];if(m)c[m.category]=(c[m.category]||0)+x.qty});$("categorySummary").innerHTML=Object.entries(c).map(x=>`<div class="category-row"><span>${x[0]}</span><b>${x[1]} unit</b></div>`).join("")||'<div class="muted">Belum ada penjualan hari ini.</div>'}
function rin(){let s=($("inSearch").value||"").toLowerCase(),r=stockIn.filter(x=>(x.product+" "+x.sku).toLowerCase().includes(s));$("stockInTable").innerHTML=r.map(x=>`<tr><td>${x.date}</td><td>${x.product}</td><td>${x.color}</td><td>${x.sku}</td><td><b>${x.qty}</b></td><td>${x.note||"-"}</td><td class="actions"><button class="btn small" onclick="editIn(${x.id})">✏ Edit</button><button class="btn small danger-btn" onclick="delIn(${x.id})">🗑 Hapus</button></td></tr>`).join("")||empty(7)}
function rout(){let s=($("outSearch").value||"").toLowerCase(),d=$("outDateFilter").value,r=stockOut.filter(x=>(!d||x.date===d)&&(x.product+" "+x.sku).toLowerCase().includes(s));$("stockOutTable").innerHTML=r.map(x=>`<tr><td>${x.date}</td><td>${x.product}</td><td>${x.color}</td><td>${x.sku}</td><td><b>${x.qty}</b></td><td>${money(x.total)}</td><td>${x.note||"-"}</td><td class="actions"><button class="btn small" onclick="editOut(${x.id})">✏ Edit</button><button class="btn small danger-btn" onclick="delOut(${x.id})">🗑 Hapus</button></td></tr>`).join("")||empty(8)}
function rlive(){let d=$("liveDate").value||today(),cat=$("liveCategory").value,col=$("liveColor").value,s=($("liveSearch").value||"").toLowerCase(),r=[];PRODUCTS.forEach(p=>COLORS.forEach(c=>{let z=sku(p[1],c),q=getStock(p[1],c,d);if((!cat||p[0]===cat)&&(!col||c===col)&&(!s||(p[1]+" "+z).toLowerCase().includes(s)))r.push({p:p[1],c,z,i:stockIn.filter(x=>x.product===p[1]&&x.color===c&&x.date<=d).reduce((a,x)=>a+x.qty,0),o:stockOut.filter(x=>x.product===p[1]&&x.color===c&&x.date<=d).reduce((a,x)=>a+x.qty,0),q})}));$("liveStockTable").innerHTML=r.map(x=>`<tr><td>${x.p}</td><td>${x.c}</td><td>${x.z}</td><td>${x.i}</td><td>${x.o}</td><td><b>${x.q}</b></td><td><span class="status ${x.q<=0?"empty":x.q<=5?"low":"ok"}">${x.q<=0?"HABIS":x.q<=5?"LOW":"AMAN"}</span></td></tr>`).join("")||empty(7)}
function rreport(){let f=$("reportFrom").value,t=$("reportTo").value,s=($("reportSearch").value||"").toLowerCase(),c=$("reportColor").value,r=stockOut.filter(x=>(!f||x.date>=f)&&(!t||x.date<=t)&&(!c||x.color===c)&&(!s||(x.product+" "+x.sku).toLowerCase().includes(s)));$("reportQty").textContent=r.reduce((a,x)=>a+x.qty,0);$("reportRevenue").textContent=money(r.reduce((a,x)=>a+x.total,0));$("reportDays").textContent=new Set(r.map(x=>x.date)).size;let d={};r.forEach(x=>{d[x.date]??={q:0,t:0};d[x.date].q+=x.qty;d[x.date].t+=x.total});$("dailyReportTable").innerHTML=Object.entries(d).sort().reverse().map(x=>`<tr><td>${x[0]}</td><td>${x[1].q}</td><td>${money(x[1].t)}</td></tr>`).join("")||empty(3);$("reportDetailTable").innerHTML=r.map(x=>`<tr><td>${x.date}</td><td>${x.product}</td><td>${x.color}</td><td>${x.sku}</td><td>${x.qty}</td><td>${money(x.total)}</td></tr>`).join("")||empty(6)}
function rprod(){let s=($("productSearch").value||"").toLowerCase();$("productsTable").innerHTML=PRODUCTS.filter(x=>(x[0]+" "+x[1]).toLowerCase().includes(s)).map(x=>`<tr><td>${x[0]}</td><td><b>${x[1]}</b></td><td>${x[1].replaceAll(" ","-")}</td></tr>`).join("");$("colorChips").innerHTML=COLORS.map(x=>`<span class="chip">${x}</span>`).join("")}
function updateTotal(){let q=+$("outQty").value||0,p=+$("outPrice").value||0;$("outTotal").value=money(q*p);if($("outProduct").value)$("availableStock").textContent=`Stock tersedia: ${getStock($("outProduct").value,$("outColor").value,$("outDate").value||today())} unit`}
async function editIn(id){let x=stockIn.find(r=>r.id===id);if(!x)return;let d=prompt("Tanggal:",x.date),q=prompt("Jumlah:",x.qty),n=prompt("Catatan:",x.note||"");if(d===null||q===null||n===null)return;q=+q;if(!d||!Number.isInteger(q)||q<1)return alert("Data tidak valid.");let z=await sb.from("stock_in").update({date:d,qty:q,note:n,sku:sku(x.product,x.color)}).eq("id",id);if(z.error)alert(z.error.message);else load()}
async function delIn(id){if(!confirm("Hapus Stock In ini?"))return;let z=await sb.from("stock_in").delete().eq("id",id);if(z.error)alert(z.error.message);else load()}
async function editOut(id){let x=stockOut.find(r=>r.id===id);if(!x)return;let d=prompt("Tanggal:",x.date),q=prompt("Qty:",x.qty),p=prompt("Harga/unit:",x.price),n=prompt("Catatan:",x.note||"");if(d===null||q===null||p===null||n===null)return;q=+q;p=+p;if(!d||!Number.isInteger(q)||q<1||p<0)return alert("Data tidak valid.");let available=getStock(x.product,x.color,d,id);if(q>available)return alert(`Stock tidak cukup. Maksimal ${available} unit.`);let z=await sb.from("stock_out").update({date:d,qty:q,price:p,total:q*p,note:n,sku:sku(x.product,x.color)}).eq("id",id);if(z.error)alert(z.error.message);else load()}
async function delOut(id){if(!confirm("Hapus penjualan ini?"))return;let z=await sb.from("stock_out").delete().eq("id",id);if(z.error)alert(z.error.message);else load()}
function downloadCSV(filename,headers,rows){let csv="\uFEFF"+[headers,...rows].map(a=>a.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n"),b=new Blob([csv],{type:"text/csv;charset=utf-8;"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=filename;a.click();URL.revokeObjectURL(a.href)}
function exportCSV(){let r=stockOut.map(x=>[x.date,x.product,x.color,x.sku,x.qty,x.total,x.note||""]);downloadCSV(`digifine-penjualan-${today()}.csv`,["Tanggal","Varian","Warna","SKU","Qty","Total","Catatan"],r)}
function exportStockInCSV(){let s=($("inSearch").value||"").toLowerCase(),r=stockIn.filter(x=>(x.product+" "+x.sku).toLowerCase().includes(s)).map(x=>[x.date,x.product,x.color,x.sku,x.qty,x.note||""]);downloadCSV(`digifine-stock-in-${today()}.csv`,["Tanggal","Varian","Warna","SKU","Qty","Catatan"],r)}
function exportLiveStockCSV(){let d=$("liveDate").value||today(),cat=$("liveCategory").value,col=$("liveColor").value,s=($("liveSearch").value||"").toLowerCase(),rows=[];PRODUCTS.forEach(p=>COLORS.forEach(c=>{let z=sku(p[1],c),q=getStock(p[1],c,d),i=stockIn.filter(x=>x.product===p[1]&&x.color===c&&x.date<=d).reduce((a,x)=>a+x.qty,0),o=stockOut.filter(x=>x.product===p[1]&&x.color===c&&x.date<=d).reduce((a,x)=>a+x.qty,0);if((!cat||p[0]===cat)&&(!col||c===col)&&(!s||(p[1]+" "+z).toLowerCase().includes(s)))rows.push([p[1],c,z,i,o,q,q<=0?"HABIS":q<=5?"LOW":"AMAN"])}));downloadCSV(`digifine-live-stock-${d}.csv`,["Varian","Warna","SKU","Stock In","Stock Out","Live Stock","Status"],rows)}
function init(){let d=today();["inDate","outDate","liveDate","reportFrom","reportTo"].forEach(id=>$(id).value=d);$("todayLabel").textContent=new Date().toLocaleDateString("id-ID",{weekday:"long",day:"2-digit",month:"short",year:"numeric"});opts("inProduct",PRODUCTS);opts("outProduct",PRODUCTS);opts("inColor",COLORS);opts("outColor",COLORS);opts("liveColor",COLORS,true);opts("reportColor",COLORS,true);opts("liveCategory",[...new Set(PRODUCTS.map(x=>x[0]))],true);$("loginForm").onsubmit=e=>{e.preventDefault();if($("username").value===KEY_USER&&$("password").value===KEY_PASS){$("loginPage").classList.add("hidden");$("appPage").classList.remove("hidden")}else $("loginError").classList.remove("hidden")};$("logoutBtn").onclick=()=>location.reload();$("resetDataBtn").onclick=async()=>{if(!confirm("Hapus semua data online?"))return;await Promise.all([sb.from("stock_in").delete().not("id","is",null),sb.from("stock_out").delete().not("id","is",null)]);load()};document.querySelectorAll(".nav-item[data-page]").forEach(b=>b.onclick=()=>showPage(b.dataset.page));$("stockInForm").onsubmit=async e=>{e.preventDefault();let p=$("inProduct").value,c=$("inColor").value;let z=await sb.from("stock_in").insert({date:$("inDate").value,product:p,color:c,qty:+$("inQty").value,note:$("inNote").value,sku:sku(p,c)});if(z.error)alert(z.error.message);else{e.target.reset();$("inDate").value=d;load()}};$("stockOutForm").onsubmit=async e=>{e.preventDefault();let p=$("outProduct").value,c=$("outColor").value,q=+$("outQty").value,date=$("outDate").value||d,price=+$("outPrice").value;if(q>getStock(p,c,date))return alert("Stock tidak cukup.");let z=await sb.from("stock_out").insert({date,product:p,color:c,qty:q,price,total:q*price,note:$("outNote").value,sku:sku(p,c)});if(z.error)alert(z.error.message);else{e.target.reset();$("outDate").value=d;$("outTotal").value="Rp 0";load()}};["outQty","outPrice","outDate","outProduct","outColor"].forEach(id=>$(id).addEventListener("input",updateTotal));["inSearch","outSearch","outDateFilter","liveDate","liveCategory","liveColor","liveSearch","reportFrom","reportTo","reportSearch","reportColor","productSearch"].forEach(id=>$(id).addEventListener("input",render));$("exportCsvBtn").onclick=exportCSV;$("exportInCsvBtn").onclick=exportStockInCSV;$("exportLiveCsvBtn").onclick=exportLiveStockCSV;load();realtime()}
init();